# Use postgres as a user credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: b4Dg3R
    ports:
      - 5431:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9081:8080
